packages:
  - apps/*
  - packages/*
catalog:
  "@orpc/server": ^1.10.0
  "@orpc/openapi": ^1.10.0
  "@orpc/zod": ^1.10.0
  better-auth: ^1.3.28
  dotenv: ^17.2.2
  zod: ^4.1.11
  typescript: ^5.8.2
  "@types/express": ^5.0.1
  "@types/node": ^22.13.11
  tsdown: ^0.15.5
  "@orpc/client": ^1.10.0
  "@prisma/client": ^6.15.0
